"""
pdf_engine.py — Reusable PDF generation engine for Termux AI Agent
===================================================================
ReportLab 5.0.1 + Python 3.14 + ARMv7 Android/Termux

Usage:
    from pdf_engine import create_pdf

    result = create_pdf(
        output="/sdcard/report.pdf",
        title="My Report",
        subtitle="Generated by AI Agent",
        content=[
            {"type": "heading",   "text": "Section 1"},
            {"type": "paragraph", "text": "Hello world."},
            {"type": "bullet",    "items": ["One", "Two", "Three"]},
        ]
    )
    print(result)  # {"status": "ok", "path": "/sdcard/report.pdf", ...}
"""

import os
import traceback
from pathlib import Path

# ── ReportLab imports ─────────────────────────────────────────────────────────
try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import cm, mm
    from reportlab.lib.colors import (
        HexColor, black, white, Color,
        darkblue, darkgrey, lightgrey, grey
    )
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, PageBreak,
        Table, TableStyle, Image as RLImage, HRFlowable,
        ListFlowable, ListItem, KeepTogether
    )
    from reportlab.platypus.flowables import Flowable
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont
except ImportError as e:
    raise ImportError(
        f"ReportLab not installed: {e}\n"
        "Install it: pip install reportlab --break-system-packages"
    )

# ── Constants ─────────────────────────────────────────────────────────────────
PAGE_WIDTH, PAGE_HEIGHT = A4

# Color palette
C_PRIMARY   = HexColor('#1a237e')   # Dark indigo
C_SECONDARY = HexColor('#283593')   # Medium indigo
C_ACCENT    = HexColor('#3949ab')   # Accent blue
C_HEADING   = HexColor('#1a237e')   # Heading color
C_SUBHEAD   = HexColor('#283593')   # Subheading
C_TEXT      = HexColor('#212121')   # Body text
C_LIGHT     = HexColor('#f5f5f5')   # Table alternate row
C_BORDER    = HexColor('#bdbdbd')   # Border color
C_TABLE_HDR = HexColor('#3949ab')   # Table header bg
C_FOOTER    = HexColor('#757575')   # Footer text


# ── Style Builder ─────────────────────────────────────────────────────────────

def _build_styles():
    """Build and return custom paragraph styles."""
    base = getSampleStyleSheet()

    styles = {}

    styles['title'] = ParagraphStyle(
        'PDFTitle',
        parent=base['Title'],
        fontSize=26,
        textColor=C_PRIMARY,
        spaceAfter=6,
        spaceBefore=0,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold',
        leading=32,
    )

    styles['subtitle'] = ParagraphStyle(
        'PDFSubtitle',
        parent=base['Normal'],
        fontSize=14,
        textColor=C_SECONDARY,
        spaceAfter=20,
        spaceBefore=0,
        alignment=TA_CENTER,
        fontName='Helvetica',
        leading=18,
    )

    styles['heading'] = ParagraphStyle(
        'PDFHeading',
        parent=base['Heading1'],
        fontSize=16,
        textColor=C_HEADING,
        spaceAfter=8,
        spaceBefore=18,
        fontName='Helvetica-Bold',
        borderPad=0,
        leading=22,
    )

    styles['subheading'] = ParagraphStyle(
        'PDFSubheading',
        parent=base['Heading2'],
        fontSize=13,
        textColor=C_SUBHEAD,
        spaceAfter=6,
        spaceBefore=12,
        fontName='Helvetica-Bold',
        leading=18,
    )

    styles['paragraph'] = ParagraphStyle(
        'PDFParagraph',
        parent=base['Normal'],
        fontSize=11,
        textColor=C_TEXT,
        spaceAfter=10,
        spaceBefore=2,
        fontName='Helvetica',
        leading=16,
        alignment=TA_JUSTIFY,
        wordWrap='LTR',
    )

    styles['bold'] = ParagraphStyle(
        'PDFBold',
        parent=styles['paragraph'],
        fontName='Helvetica-Bold',
    )

    styles['italic'] = ParagraphStyle(
        'PDFItalic',
        parent=styles['paragraph'],
        fontName='Helvetica-Oblique',
    )

    styles['bullet_item'] = ParagraphStyle(
        'PDFBulletItem',
        parent=base['Normal'],
        fontSize=11,
        textColor=C_TEXT,
        fontName='Helvetica',
        leading=15,
        spaceAfter=2,
    )

    styles['caption'] = ParagraphStyle(
        'PDFCaption',
        parent=base['Normal'],
        fontSize=9,
        textColor=C_FOOTER,
        fontName='Helvetica-Oblique',
        alignment=TA_CENTER,
        spaceAfter=8,
        spaceBefore=2,
    )

    styles['code'] = ParagraphStyle(
        'PDFCode',
        parent=base['Code'],
        fontSize=9,
        fontName='Courier',
        backColor=HexColor('#f5f5f5'),
        borderPad=6,
        spaceAfter=10,
        spaceBefore=4,
        leading=14,
        textColor=HexColor('#333333'),
    )

    return styles


# ── Header / Footer Canvas ────────────────────────────────────────────────────

def _make_header_footer(header_text, footer_text, show_page_numbers):
    """Return an onPage callback that draws header and footer on every page."""

    def _draw(canvas, doc):
        canvas.saveState()
        w, h = doc.pagesize

        # ── Header ──
        if header_text:
            canvas.setFillColor(C_PRIMARY)
            canvas.rect(0, h - 38, w, 38, fill=1, stroke=0)
            canvas.setFillColor(white)
            canvas.setFont('Helvetica-Bold', 10)
            canvas.drawString(20, h - 24, str(header_text))

        # ── Footer ──
        footer_y = 25
        canvas.setStrokeColor(C_BORDER)
        canvas.line(20, footer_y + 10, w - 20, footer_y + 10)
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(C_FOOTER)

        if footer_text:
            canvas.drawString(20, footer_y, str(footer_text))

        if show_page_numbers:
            page_str = f'Page {doc.page}'
            canvas.drawRightString(w - 20, footer_y, page_str)

        canvas.restoreState()

    return _draw


# ── Content → Flowable Converters ─────────────────────────────────────────────

def _safe_text(text):
    """Escape XML special chars for ReportLab Paragraph."""
    if not isinstance(text, str):
        text = str(text)
    text = text.replace('&', '&amp;')
    text = text.replace('<', '&lt;')
    text = text.replace('>', '&gt;')
    return text


def _convert_title(item, styles):
    flowables = []
    text = _safe_text(item.get('text', ''))
    if text:
        flowables.append(Paragraph(text, styles['title']))
        flowables.append(HRFlowable(
            width='100%', thickness=2,
            color=C_PRIMARY, spaceAfter=4
        ))
    return flowables


def _convert_subtitle(item, styles):
    text = _safe_text(item.get('text', ''))
    if not text:
        return []
    return [
        Paragraph(text, styles['subtitle']),
        Spacer(1, 8),
    ]


def _convert_heading(item, styles):
    text = _safe_text(item.get('text', ''))
    if not text:
        return []
    return [
        Spacer(1, 4),
        Paragraph(text, styles['heading']),
        HRFlowable(width='100%', thickness=0.5, color=C_BORDER, spaceAfter=4),
    ]


def _convert_subheading(item, styles):
    text = _safe_text(item.get('text', ''))
    if not text:
        return []
    return [Paragraph(text, styles['subheading'])]


def _convert_paragraph(item, styles):
    text = _safe_text(item.get('text', ''))
    if not text:
        return []
    style_key = item.get('style', 'paragraph')
    style = styles.get(style_key, styles['paragraph'])
    return [Paragraph(text, style)]


def _convert_bold(item, styles):
    text = _safe_text(item.get('text', ''))
    if not text:
        return []
    return [Paragraph(f'<b>{text}</b>', styles['paragraph'])]


def _convert_italic(item, styles):
    text = _safe_text(item.get('text', ''))
    if not text:
        return []
    return [Paragraph(f'<i>{text}</i>', styles['paragraph'])]


def _convert_bullet(item, styles):
    """Unordered bullet list."""
    items = item.get('items', [])
    if not items:
        return []

    list_items = []
    for it in items:
        text = _safe_text(str(it))
        list_items.append(
            ListItem(
                Paragraph(text, styles['bullet_item']),
                bulletColor=C_PRIMARY,
                leftIndent=20,
            )
        )

    return [
        ListFlowable(
            list_items,
            bulletType='bullet',
            bulletColor=C_PRIMARY,
            bulletFontSize=10,
            bulletOffsetY=-1,
            leftIndent=10,
            spaceAfter=8,
        )
    ]


def _convert_numbered(item, styles):
    """Ordered / numbered list."""
    items = item.get('items', [])
    if not items:
        return []

    list_items = []
    for it in items:
        text = _safe_text(str(it))
        list_items.append(
            ListItem(
                Paragraph(text, styles['bullet_item']),
                leftIndent=20,
            )
        )

    return [
        ListFlowable(
            list_items,
            bulletType='1',
            bulletColor=C_PRIMARY,
            bulletFontSize=10,
            leftIndent=10,
            spaceAfter=8,
        )
    ]


def _convert_table(item, styles):
    """Table with headers and rows."""
    headers = item.get('headers', [])
    rows    = item.get('rows', [])

    if not rows and not headers:
        return []

    # Build data grid
    data = []
    if headers:
        data.append([str(h) for h in headers])
    for row in rows:
        data.append([str(c) for c in row])

    if not data:
        return []

    # Column widths — distribute evenly across usable width
    usable_w = PAGE_WIDTH - 4 * cm  # 2cm margins each side
    col_count = max(len(r) for r in data)
    col_w = usable_w / col_count if col_count else usable_w

    table_style = TableStyle([
        # Header row
        ('BACKGROUND',   (0, 0), (-1, 0),  C_TABLE_HDR),
        ('TEXTCOLOR',    (0, 0), (-1, 0),  white),
        ('FONTNAME',     (0, 0), (-1, 0),  'Helvetica-Bold'),
        ('FONTSIZE',     (0, 0), (-1, 0),  10),
        ('TOPPADDING',   (0, 0), (-1, 0),  8),
        ('BOTTOMPADDING',(0, 0), (-1, 0),  8),
        ('ALIGN',        (0, 0), (-1, 0),  'CENTER'),

        # Data rows
        ('FONTNAME',     (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE',     (0, 1), (-1, -1), 10),
        ('TOPPADDING',   (0, 1), (-1, -1), 5),
        ('BOTTOMPADDING',(0, 1), (-1, -1), 5),
        ('ALIGN',        (0, 1), (-1, -1), 'LEFT'),

        # Alternating row colors
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [white, C_LIGHT]),

        # Borders
        ('GRID',         (0, 0), (-1, -1), 0.5, C_BORDER),
        ('BOX',          (0, 0), (-1, -1), 1.0, C_PRIMARY),
        ('LINEBELOW',    (0, 0), (-1, 0),  1.5, C_PRIMARY),

        # Valign
        ('VALIGN',       (0, 0), (-1, -1), 'MIDDLE'),
        ('WORDWRAP',     (0, 0), (-1, -1), True),
    ])

    col_widths = [col_w] * col_count
    tbl = Table(data, colWidths=col_widths, repeatRows=1 if headers else 0)
    tbl.setStyle(table_style)

    return [Spacer(1, 6), tbl, Spacer(1, 10)]


def _convert_image(item, styles):
    """Embed image (optional). Gracefully skip if missing."""
    path = item.get('path', '').strip()
    if not path:
        return []

    path = os.path.expanduser(path)
    if not os.path.exists(path):
        # Return a warning paragraph instead of crashing
        return [Paragraph(
            f'<i>[Image not found: {_safe_text(path)}]</i>',
            styles['caption']
        )]

    try:
        max_w = item.get('width', PAGE_WIDTH - 4 * cm)
        max_h = item.get('height', PAGE_HEIGHT * 0.4)

        img = RLImage(path)
        iw, ih = img.drawWidth, img.drawHeight

        # Scale proportionally
        ratio = min(max_w / iw, max_h / ih, 1.0)
        img.drawWidth  = iw * ratio
        img.drawHeight = ih * ratio

        flowables = [Spacer(1, 6), img]

        caption = item.get('caption', '')
        if caption:
            flowables.append(Paragraph(_safe_text(caption), styles['caption']))

        flowables.append(Spacer(1, 6))
        return flowables

    except Exception as e:
        return [Paragraph(
            f'<i>[Image load error: {_safe_text(str(e))}]</i>',
            styles['caption']
        )]


def _convert_hr(item, styles):
    return [
        Spacer(1, 4),
        HRFlowable(width='100%', thickness=1, color=C_BORDER),
        Spacer(1, 4),
    ]


def _convert_spacer(item, styles):
    height = item.get('height', 12)
    return [Spacer(1, height)]


def _convert_pagebreak(item, styles):
    return [PageBreak()]


def _convert_code(item, styles):
    text = item.get('text', '')
    # Preserve indentation — replace spaces with non-breaking
    text = _safe_text(text).replace('\n', '<br/>')
    return [Paragraph(text, styles['code'])]


# ── Dispatcher ────────────────────────────────────────────────────────────────

CONVERTERS = {
    'title':       _convert_title,
    'subtitle':    _convert_subtitle,
    'heading':     _convert_heading,
    'subheading':  _convert_subheading,
    'paragraph':   _convert_paragraph,
    'bold':        _convert_bold,
    'italic':      _convert_italic,
    'bullet':      _convert_bullet,
    'numbered':    _convert_numbered,
    'table':       _convert_table,
    'image':       _convert_image,
    'hr':          _convert_hr,
    'spacer':      _convert_spacer,
    'pagebreak':   _convert_pagebreak,
    'page_break':  _convert_pagebreak,
    'code':        _convert_code,
}


def _content_to_flowables(content, styles):
    """Convert list of content dicts → list of ReportLab Flowables."""
    flowables = []
    errors    = []

    for i, item in enumerate(content):
        if not isinstance(item, dict):
            errors.append(f"Item #{i} is not a dict (got {type(item).__name__})")
            continue

        item_type = item.get('type', '').lower().strip()
        if not item_type:
            errors.append(f"Item #{i} missing 'type' key")
            continue

        converter = CONVERTERS.get(item_type)
        if converter is None:
            errors.append(f"Item #{i}: unknown type '{item_type}' (skipped)")
            continue

        try:
            result = converter(item, styles)
            if result:
                flowables.extend(result)
        except Exception as e:
            errors.append(f"Item #{i} ({item_type}): {e}")

    return flowables, errors


# ── Main API ──────────────────────────────────────────────────────────────────

def create_pdf(
    output,
    content=None,
    title=None,
    subtitle=None,
    header=None,
    footer=None,
    show_page_numbers=True,
    margins=None,
    overwrite=False,
    author=None,
    subject=None,
):
    """
    Generate a PDF from structured content.

    Parameters
    ----------
    output : str
        Output file path (e.g. "/sdcard/report.pdf")
    content : list of dict
        Structured content blocks. Each dict has at minimum {"type": "..."}
        See module docstring for all supported types.
    title : str, optional
        Document title (added as first content block automatically).
    subtitle : str, optional
        Document subtitle (added after title automatically).
    header : str, optional
        Text shown in page header band on every page.
    footer : str, optional
        Text shown in page footer on every page.
    show_page_numbers : bool
        Show "Page N" in footer (default: True).
    margins : dict, optional
        Keys: left, right, top, bottom (in cm). Default: 2cm each.
    overwrite : bool
        If False (default), raise error if output file already exists.
    author : str, optional
        PDF metadata author.
    subject : str, optional
        PDF metadata subject.

    Returns
    -------
    dict
        {"status": "ok", "path": ..., "pages": ..., "warnings": [...]}
        or
        {"status": "error", "message": ..., "traceback": ...}
    """
    try:
        # ── Validate output path ──
        output = os.path.expanduser(str(output).strip())
        if not output:
            return {"status": "error", "message": "output path is empty"}

        if not output.lower().endswith('.pdf'):
            output = output + '.pdf'

        parent = os.path.dirname(output) or '.'
        try:
            os.makedirs(parent, exist_ok=True)
        except PermissionError as e:
            return {"status": "error", "message": f"Permission denied creating directory: {parent} — {e}"}

        if os.path.exists(output) and not overwrite:
            return {
                "status": "error",
                "message": (
                    f"File already exists: {output}\n"
                    "Pass overwrite=True to replace it."
                )
            }

        # ── Validate content ──
        content = content or []
        if not isinstance(content, list):
            return {"status": "error", "message": "'content' must be a list of dicts"}

        # ── Build styles ──
        styles = _build_styles()

        # ── Margins ──
        m = margins or {}
        left   = m.get('left',   2) * cm
        right  = m.get('right',  2) * cm
        top    = m.get('top',    2) * cm
        bottom = m.get('bottom', 2) * cm
        # Extra space for header/footer
        if header:
            top    = max(top,    2.5 * cm)
        if footer or show_page_numbers:
            bottom = max(bottom, 1.8 * cm)

        # ── Create document ──
        doc = SimpleDocTemplate(
            output,
            pagesize=A4,
            leftMargin=left,
            rightMargin=right,
            topMargin=top,
            bottomMargin=bottom,
            title=title or 'Document',
            author=author or 'AI Agent',
            subject=subject or '',
        )

        # ── Assemble flowables ──
        flowables = []
        all_warnings = []

        # Auto-inject title/subtitle from params
        if title:
            t_flowables, errs = _content_to_flowables(
                [{"type": "title", "text": title}], styles
            )
            flowables.extend(t_flowables)
            all_warnings.extend(errs)

        if subtitle:
            t_flowables, errs = _content_to_flowables(
                [{"type": "subtitle", "text": subtitle}], styles
            )
            flowables.extend(t_flowables)
            all_warnings.extend(errs)

        if (title or subtitle) and content:
            flowables.append(Spacer(1, 12))

        # Convert main content
        if content:
            body_flowables, errs = _content_to_flowables(content, styles)
            flowables.extend(body_flowables)
            all_warnings.extend(errs)

        # Must have at least one flowable
        if not flowables:
            return {"status": "error", "message": "No content to render — document would be empty"}

        # ── Build & save PDF ──
        on_page = _make_header_footer(
            header_text=header,
            footer_text=footer,
            show_page_numbers=show_page_numbers,
        )

        doc.build(flowables, onFirstPage=on_page, onLaterPages=on_page)

        # ── Success ──
        file_size = os.path.getsize(output)
        return {
            "status":   "ok",
            "path":     output,
            "size":     file_size,
            "warnings": all_warnings,
        }

    except PermissionError as e:
        return {"status": "error", "message": f"Permission error: {e}"}
    except Exception as e:
        return {
            "status":    "error",
            "message":   str(e),
            "traceback": traceback.format_exc(),
        }


# ── CLI / Quick test ──────────────────────────────────────────────────────────

if __name__ == '__main__':
    import sys, json

    # If called with JSON argument: python pdf_engine.py '{"output":...}'
    if len(sys.argv) > 1:
        try:
            kwargs = json.loads(sys.argv[1])
            result = create_pdf(**kwargs)
            print(json.dumps(result, indent=2))
        except Exception as e:
            print(json.dumps({"status": "error", "message": str(e)}))
    else:
        # Self-test
        result = create_pdf(
            output="/tmp/pdf_engine_selftest.pdf",
            title="Self-Test",
            subtitle="pdf_engine.py is working",
            content=[{"type": "paragraph", "text": "Engine loaded successfully."}],
            overwrite=True,
        )
        print(result)
